### PR TITLE
Over charge autos

### PR DESCRIPTION
**Pull request by foehammer127**
These are the over charge autos

### CODE REVIEW

**Comment by foehammer127** [comment]
Solves #117
Relies on a Intake Event

**Comment by mvog2501** [comment]
Let's wait a bit on this one. I just pushed some changes that fix minor issues like the heading being wrong on a few paths (causes a bounce). I'm slightly worried that having pathplanner navigate over the charge station may not be as easy as anticipated. What we may need to do is something similar to the start balance command where it drives until the tilt is right and then resets the position. Great work so far!

**Comment by foehammer127** [comment]
Thanks, I was also worried about the charge station.

**Comment by foehammer127** [comment]
They never were tested, although in theory they should work fine.

**Pull request closed without merging**
